name: CI/CD Pipeline # Combined workflow for integration and deployment

on:
  push:
    branches: ["main"] # Trigger on push to main
  pull_request:
    branches: ["main"] # Trigger on PR targeting main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Build the application
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Run unit tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, unit-tests] # Ensure deploy runs after build and tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t siddongre358/my-app:latest .
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker image
        run: docker push siddongre358/my-app:latest