name: Deploy

on:
  push:
    branches: ["main"] # Trigger workflow only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job

    steps:
      - uses: actions/checkout@v4 # Checkout the repository code into the runner
      - run: docker build -t siddongre358/my-app:latest . # Build Docker image with 'latest' tag
      - run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin # Log in to DockerHub securely using secrets
      - run: docker push siddongre358/my-app:latest # Push Docker image to DockerHub
